packages:
  # - clients/imodelhub
  # - core/backend
  # - core/bentley
  # - core/common
  # - core/ecschema-editing
  # - core/ecschema-locaters
  # - core/ecschema-metadata
  # - core/ecschema-rpc/common
  # - core/ecschema-rpc/impl
  # - core/electron
  # - core/express-server
  # - core/extension
  # - core/frontend
  # - core/frontend-devtools
  # - core/geometry
  # - core/hypermodeling
  # - core/i18n
  # - core/markup
  # - core/mobile
  # - core/orbitgt
  # - core/quantity
  # - core/telemetry
  # - core/transformer
  # - core/webgl-compatibility
  # - domains/analytical/backend
  # - domains/linear-referencing/backend
  # - domains/linear-referencing/common
  # - domains/physical-material/backend
  # - editor/backend
  # - editor/common
  # - editor/frontend
  # - example-code/app
  # - example-code/snippets
  # - extensions/geonames
  # - extensions/map-layers
  # - extensions/map-layers-auth
  # - extensions/test-extension
  # - full-stack-tests/backend
  # - full-stack-tests/core
  # - full-stack-tests/ecschema-rpc-interface
  # - full-stack-tests/presentation
  # - full-stack-tests/rpc
  # - full-stack-tests/rpc-interface
  # - full-stack-tests/ui
  # - presentation/backend
  # - presentation/common
  # - presentation/components
  # - presentation/frontend
  # - presentation/opentelemetry
  # - presentation/testing
  # - test-apps/appui-test-app/appui-test-providers
  # - test-apps/appui-test-app/connected
  # - test-apps/appui-test-app/standalone
  # - test-apps/display-performance-test-app
  # - test-apps/display-test-app
  # - test-apps/export-gltf
  # - test-apps/imjs-importer
  # - test-apps/imodel-from-geojson
  # - test-apps/imodel-from-orbitgt
  # - test-apps/imodel-from-reality-model
  # - test-apps/imodel-transformer
  # - test-apps/presentation-test-app
  # - test-apps/ui-items-providers-test
  # - test-apps/ui-test-app
  # - tools/backend-webpack
  # - tools/build
  # - tools/certa
  # - tools/ecschema2ts
  # - tools/eslint-plugin
  # - tools/internal
  # - tools/perf-tools
  # - tools/webpack-core
  # - ui/appui-abstract
  # - ui/appui-layout-react
  # - ui/appui-react
  # - ui/components-react
  # - ui/core-react
  # - ui/imodel-components-react
  # - utils/workspace-editor

  - clients/*
  - core/**
  - domains/**
  - editor/**
  - example-code/**
  - extensions/*
  - full-stack-tests/*
  - presentation/*
  - test-apps/**
  - tools/*
  - ui/*
  - utils/*