# iModel.js Docs CI Build

trigger:
  - master
  - release/*

pr:
  drafts: false
  branches:
    include:
      - master
      - release/*

jobs:
  - job:
    workspace:
      clean: all
    pool:
      name: iModelTechCI
      demands: Agent.OS -equals Windows_NT

    steps:
      - checkout: self
        clean: true
      - task: NodeTool@0
        displayName: Use Node 12.17.0
        inputs:
          versionSpec: 12.17.0
          checkLatest: true
      - script: |
          git config --local user.email imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin
        displayName: Setup git config

      - template: ../templates/docs-build.yaml

      - task: Npm@1
        displayName: npm audit
        inputs:
          command: custom
          verbose: false
          customCommand: "audit --registry=https://registry.npmjs.org/ --audit-level=high"
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'))

      - task: ms-codeanalysis.vss-microsoft-security-code-analysis-devops.build-task-credscan.CredScan@2
        displayName: Run Credential Scanner
        inputs:
          scanFolder: $(Agent.BuildDirectory)/tempDocsBuild
        condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/2')))

      - task: PublishPipelineArtifact@1
        displayName: Publish Pipeline Artifact - .updated.json
        inputs:
          targetPath: $(System.ArtifactsDirectory)/staging/config/.updated.json
          artifact: .updated.json
        condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release')))

      - task: PublishPipelineArtifact@1
        displayName: Publish Pipeline Artifact - Credential Scanner
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)/../_sdt/logs/CredentialScanner
          artifact: CredentialScanner
        condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release')))

      - task: DownloadPipelineArtifact@2
        displayName: Download Pipeline Artifact - Nuget Spec
        inputs:
          buildType: specific
          project: 2c48216e-e72f-48b4-a4eb-40ff1c04e8e4
          definition: 1830
        condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release')))

      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: Replace tokens in NugetPackage.nuspec
        inputs:
          targetFiles: $(Agent.BuildDirectory)/DocsNugetSpecFile/NugetPackage.nuspec
        condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release')))

      - task: DeleteFiles@1
        displayName: Delete files from $(Agent.BuildDirectory)/tempDocsBuild/public_build
        inputs:
          SourceFolder: $(Agent.BuildDirectory)/tempDocsBuild/public_build/
          Contents: index.html
        condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release')))

      - task: NuGetToolInstaller@0
        displayName: Use NuGet 4.9.2
        inputs:
          versionSpec: 4.9.2
        condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release')))

      - task: NuGetCommand@2
        displayName: NuGet pack
        inputs:
          command: pack
          packagesToPack: $(Agent.BuildDirectory)/DocsNugetSpecFile/NugetPackage.nuspec
          versioningScheme: byBuildNumber
        condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/2')))

      - task: PublishPipelineArtifact@1
        displayName: "Publish Pipeline Artifact - iModel.js Documentation .nupkg"
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)/iModeljs.Documentation.$(Build.BuildNumber).nupkg
          artifact: iModeljsDocumentationFiles_$(Build.BuildNumber)
        condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/2')))
