# This template handles gathering all of the raw docs artifacts into a single staging directory
# to allow them to be processed for publication.
#
# Note: This step has a dependency on the

parameters:
  - name: workingDir
    type: string
    default: $(System.DefaultWorkingDirectory)
  - name: stagingDir
    type: string
    default: $(System.ArtifactsDirectory)/staging/

steps:
  ## Why is this needed??
  - task: PublishPipelineArtifact@1
    displayName: Publish Pipeline Artifact - TypeDoc json
    inputs:
      targetPath: ${{ parameters.workingDir }}/generated-docs
      artifact: TypeDoc json
    enabled: false

  - script: |
      mkdir $${{ parameters.stagingDir }}/reference/

      echo Copying all reference files to staging
      cp -R generated-docs/core/ $${{ parameters.stagingDir }}/reference/
      cp -R generated-docs/clients/ $${{ parameters.stagingDir }}/reference/
      cp -R generated-docs/ui/ $${{ parameters.stagingDir }}/reference/
      cp -R generated-docs/presentation/ $${{ parameters.stagingDir }}/reference/
      cp -R generated-docs/domains/ $${{ parameters.stagingDir }}/reference/

      echo Copying extracted code to staging
      mkdir $${{ parameters.stagingDir }}/extract/
      cp -R generated-docs/extract/ $${{ parameters.stagingDir }}/extract/

      echo Copying all files from \docs folder
      cp -R docs/ $${{ parameters.stagingDir }}/
    workingDirectory: ${{ parameters.workingDir }}
    displayName: Copy Reference files to Staging

  # BIS Docs are pulled from a separate internal build currently. This will change in the future
  - task: DownloadBuildArtifacts@0
    displayName: Download Bis Docs Artifacts
    inputs:
      buildType: specific
      project: 2c48216e-e72f-48b4-a4eb-40ff1c04e8e4
      pipeline: 1633
      buildVersionToDownload: specific
      buildId: 709524
      artifactName: Bis Docs

  - task: CopyFiles@2
    displayName: Copy Bis Docs to staging
    inputs:
      SourceFolder: "$(System.ArtifactsDirectory)/Bis Docs"
      TargetFolder: ${{ parameters.stagingDir }}/bis/domains/

  # The .updated.json is cached in order to let BeMetalsmith know what needs to be re-built.
  - task: DownloadPipelineArtifact@2
    displayName: Download Pipeline Artifact - .updated.json
    inputs:
      runVersion: latestFromBranch
      artifactName: .updated.json
      targetPath: ${{ parameters.stagingDir }}/config/
