# This template handles gathering all of the raw docs artifacts into a single staging directory
# to allow them to be processed for publication.

parameters:
  - name: workingDir
    type: string
    default: $(Pipeline.Workspace)/itwinjs-core
  - name: stagingDir
    type: string
    default: $(System.ArtifactsDirectory)/staging/
  - name: useCoreDocsArtifact
    type: boolean
    default: false

steps:
  # build script exists outside of any project so manually install fs-extra
  - download: generated-docs
    artifact: Core Generated Docs
    condition: and(succeeded(), eq('${{ parameters.useCoreDocsArtifact }}', true))
  - download: AppUI Docs
    artifact: AppUI Docs
  - download: Bis Docs
    artifact: Bis Docs
  - download: Presentation Docs
    artifact: Presentation Docs
  - download: Transformer Docs
    artifact: Transformer Docs
  - download: iTwin-Auth-Clients Docs
    artifact: iTwin-Auth-Clients Docs

  - script: npm install fs-extra
    displayName: Install fs-extra
    workingDirectory: ${{ parameters.workingDir }}

  # Call the copying script
  - script: node common/scripts/copyReferenceFilesToStaging.js ${{ parameters.stagingDir }}
    displayName: Copy Reference files to Staging
    workingDirectory: ${{ parameters.workingDir }}
    condition: and(succeeded(), eq('${{ parameters.useCoreDocsArtifact }}', false))

  - task: CopyFiles@2
    displayName: Copy generated docs artifact to staging
    inputs:
      SourceFolder: $(Pipeline.Workspace)/generated-docs/Core Generated Docs
      TargetFolder: ${{ parameters.stagingDir }}
      OverWrite: true
    condition: and(succeeded(), eq('${{ parameters.useCoreDocsArtifact }}', true))

  # Copy AppUI Docs artifact
  - task: CopyFiles@2
    displayName: Copy AppUI Docs to staging
    inputs:
      SourceFolder: $(Pipeline.Workspace)/AppUI Docs/AppUI Docs
      TargetFolder: ${{ parameters.stagingDir }}
      OverWrite: true

  # Copy BIS Docs artifact
  - task: CopyFiles@2
    displayName: Copy Bis Docs to staging
    inputs:
      SourceFolder: $(Pipeline.Workspace)/Bis Docs/Bis Docs
      TargetFolder: ${{ parameters.stagingDir }}/bis/domains/

  # Copy Presentation Docs artifact
  - task: CopyFiles@2
    displayName: Copy Presentation Docs to staging
    inputs:
      SourceFolder: $(Pipeline.Workspace)/Presentation Docs/Presentation Docs
      TargetFolder: ${{ parameters.stagingDir }}
      OverWrite: true

  # Copy Transformer Docs artifact
  - task: CopyFiles@2
    displayName: Copy Transformer Docs to staging
    inputs:
      SourceFolder: $(Pipeline.Workspace)/Transformer Docs/Transformer Docs
      TargetFolder: ${{ parameters.stagingDir }}
      OverWrite: true

  # Copy Auth Clients artifact
  - task: CopyFiles@2
    displayName: Copy Auth Clients Docs to staging
    inputs:
      SourceFolder: $(Pipeline.Workspace)/iTwin-Auth-Clients Docs/iTwin-Auth-Clients Docs
      TargetFolder: ${{ parameters.stagingDir }}/reference/

  # The .updated.json is cached to track when the docs were last updated
  - task: DownloadPipelineArtifact@2
    displayName: Download Pipeline Artifact - .updated.json
    inputs:
      buildType: specific
      project: 2c48216e-e72f-48b4-a4eb-40ff1c04e8e4
      pipeline: 7436 # iTwin.js/Docs/iTwin.js Docs - YAML
      buildVersionToDownload: latestFromBranch
      branchName: refs/heads/master
      artifactName: .updated.json
      targetPath: ${{ parameters.stagingDir }}/config/
