# Triggered on a new release git tag pushed, starts the final steps of a release.
#
# Steps currently include
#   1. Cherry-pick changelogs, change history, and other doc updates to master

name: Finalize Release

on:
  workflow_dispatch:
  push:
    branches:
    - 'release/*'
    paths:
    - '**/CHANGELOG.md'

jobs:
  finalize:
    name: Cherry-pick Changelogs to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.IMJS_ADMIN_GH_TOKEN }}
          ref: ${{ github.ref }} # checkouts the branch that triggered the workflow
          fetch-depth: 0
      - name: Set Git Config
        run: |
          git config --local user.email 38288322+imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin
      - name: Cherry-pick changelogs
        run: |
          npm i -g zx
          npm install -g @microsoft/rush
          zx ./.github/workflows/automation-scripts/update-changelogs.mjs
        shell: bash {0}
      - name: Push to master
        run: git push https://$(GITHUBTOKEN)@github.com/iTwin/itwinjs-core HEAD:master
